api/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('confirm_booking/', confirm_booking, name='confirm_booking'),
    path('cancel_booking/', cancel_booking, name='cancel_booking'),
    path('check_masters/', check_masters, name='check_masters'),
    path('check_booked_dates/', check_booked_dates, name='check_booked_dates'),
]

barbershop/urls.py
from django.urls import path
 
from .views import *
from . import views
 
urlpatterns = [
    path('', barbershop, name='barbershop'), 
    path('barberbooking', barberbooking, name='barberbooking'), 
    path('verify', verify, name='verify'), 

    path('get-master-data/', get_master_data, name='get_master_data'),
    path('verify_record/', verify_record, name='verify_record'),
    path('privacy_policy/', privacy_policy, name='privacy_policy'),
    
    path('confirmation/', views.confirmation_view, name='confirmation'),

    path('send-telegram-message/', send_telegram_message, name='send_telegram_message'), 
    path('send_booking_to_telegram/', send_booking_to_telegram, name='send_booking_to_telegram'),  
]

inetiv_barber/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve as media_serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('barbershop.urls')),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [
        re_path(r'^%s(?P<path>.*)$' % settings.MEDIA_URL.lstrip('/'), media_serve, {'document_root': settings.MEDIA_ROOT}),
    ]

barbershop/models.py
from django.db import models
from django.core.exceptions import ValidationError
from multiselectfield import MultiSelectField

# Режим работы и адрес
class InitialData(models.Model):
    address = models.CharField("Адрес", max_length=255)
    phone = models.CharField("Телефон", max_length=20)
    working_hours = models.TextField("Режим работы")

    class Meta:
        verbose_name = "Режим работы и адрес (общие)"
        verbose_name_plural = "Режим работы и адрес (общие)"

    def __str__(self):
        return f'{self.working_hours}'

    def save(self, *args, **kwargs):
        if InitialData.objects.exists() and not self.pk:
            raise ValidationError("Можно добавить только одну запись в таблицу 'Режим работы и адрес'")
        super(InitialData, self).save(*args, **kwargs)


# Услуги
class ServiceType(models.Model):
    service_name = models.CharField("Название услуги", max_length=255)
    service_description = models.TextField("Описание услуги")
    service_price_time = models.CharField("Стоимость и время", max_length=255)
    service_image = models.ImageField("Изображение", upload_to='service_images/')

    class Meta:
        verbose_name = "виды услуг (общие)"
        verbose_name_plural = "виды услуг (общие)"

    def __str__(self):
        return self.service_name
    
# FAQ
class FAQ(models.Model):
    question = models.CharField("Вопрос", max_length=255)
    answer = models.TextField("Ответ")

    class Meta:
        verbose_name = "Часто задаваемый вопрос"
        verbose_name_plural = "Часто задаваемые вопросы"

    def __str__(self):
        return self.question

# Галерея
class SliderImage(models.Model):
    image = models.ImageField("Изображение", upload_to='slider_images/')
    description = models.TextField("Описание", blank=True)

    class Meta:
        verbose_name = "Слайд"
        verbose_name_plural = "Слайды"

    def __str__(self):
        return f"Слайд {self.id}"
    

# Отзывы
class Review(models.Model):
    avatar = models.ImageField("Аватарка", upload_to='review_avatars/')
    name = models.CharField("Имя", max_length=255)
    review_text = models.TextField("Текст отзыва")

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

    def __str__(self):
        return f"Отзыв от {self.name}"


# Таблицы для мастеров
class Master(models.Model):
    name = models.CharField(max_length=100, verbose_name="Имя мастера")
    specialty = models.CharField(max_length=100, verbose_name="Специальность мастера")
    large_photo = models.ImageField(upload_to='masters/large_photos/', verbose_name="Большая фотография", blank=True, null=True)
    avatar = models.ImageField(upload_to='masters/avatars/', verbose_name="Аватар", blank=True, null=True)

    class Meta:
        verbose_name = "Мастер"
        verbose_name_plural = "Мастера"

    def __str__(self):
        return self.name


class Contact(models.Model):
    master = models.ForeignKey(Master, on_delete=models.CASCADE, verbose_name="Мастер")
    phone = models.CharField(max_length=20, verbose_name="Мобильный телефон")
    telegram = models.URLField(verbose_name="Телеграм")
    instagram = models.URLField(verbose_name="Инстаграм")
    tiktok = models.URLField(verbose_name="ТикТок")

    class Meta:
        verbose_name = "Контакт"
        verbose_name_plural = "Контакты"

    def __str__(self):
        return f"Контакты мастера {self.master.name}"



class WorkingHours(models.Model):
    master = models.ForeignKey(Master, on_delete=models.CASCADE, verbose_name="Мастер")

    DAYS = [
        ('mon', 'Понедельник'),
        ('tue', 'Вторник'),
        ('wed', 'Среда'),
        ('thu', 'Четверг'),
        ('fri', 'Пятница'),
        ('sat', 'Суббота'),
        ('sun', 'Воскресенье'),
    ]

    # Добавление чекбоксов для каждого дня
    for day, display_name in DAYS:
        locals()[f"{day}_is_working"] = models.BooleanField(default=True, verbose_name=f"{display_name} - рабочий день")
        locals()[f"{day}_start_time"] = models.TimeField(verbose_name=f"Начало дня", default="09:00")
        locals()[f"{day}_end_time"] = models.TimeField(verbose_name=f"Конец дня", default="18:00")

    def save(self, *args, **kwargs):
        # Установка времени начала и окончания на 00:00, если день не рабочий
        for day, display_name in self.DAYS:
            if not getattr(self, f"{day}_is_working"):
                setattr(self, f"{day}_start_time", "00:00")
                setattr(self, f"{day}_end_time", "00:00")

        super(WorkingHours, self).save(*args, **kwargs) 

    def clean(self):
        for day, display_name in self.DAYS:
            self.validate_day_time(day, display_name)

    def validate_day_time(self, day, display_name):
        start_time = getattr(self, f"{day}_start_time")
        end_time = getattr(self, f"{day}_end_time")
        
        # Дополнительная проверка, если день не рабочий
        if not getattr(self, f"{day}_is_working"):
            return 

        if end_time <= start_time:
            raise ValidationError(f'Время окончания рабочего дня в {display_name} должно быть больше времени начала.')

    def __str__(self):
        return f"{self.master.name}: " + ", ".join(
            f"{display_name} - {getattr(self, f'{day}_start_time')} - {getattr(self, f'{day}_end_time')}"
            for day, display_name in self.DAYS
        )

    class Meta:
        verbose_name = "Рабочие часы"
        verbose_name_plural = "Рабочие часы"

class Service(models.Model):
    DURATION_CHOICES = [
        (30, '30'),
        (60, '60'),
        (90, '90'),
    ]
    master = models.ForeignKey(Master, on_delete=models.CASCADE, verbose_name="Мастер")
    service_name = models.CharField(max_length=100, verbose_name="Название услуги")
    price = models.IntegerField(verbose_name="Стоимость")
    duration = models.IntegerField(choices=DURATION_CHOICES, verbose_name="Время выполнения")

    class Meta:
        verbose_name = "Услуга"
        verbose_name_plural = "Услуги"

    def __str__(self):
        return f"{self.service_name}"

# бронирование
class BookedTime(models.Model):
    master = models.ForeignKey(Master, on_delete=models.CASCADE, related_name="booked_times", verbose_name="Мастер")
    date = models.DateField(verbose_name="Дата")
    time = models.TimeField(verbose_name="Время")
    service = models.ForeignKey(Service, on_delete=models.CASCADE, verbose_name="Услуга")  # Изменено на ForeignKey
    cost = models.CharField(max_length=255, verbose_name="Стоимость", blank=True, null=True)
    duration = models.IntegerField(choices=[(30, '30 минут'), (60, '1 час'), (90, '1 час 30 минут')], verbose_name="Длительность", blank=True, null=True)
    is_booked = models.BooleanField(default=True, verbose_name="Забронировано")
    client_name = models.CharField(max_length=255, verbose_name="Имя клиента", blank=True, null=True)  # Новое поле
    client_contact = models.CharField(max_length=255, verbose_name="Контакт клиента", blank=True, null=True)  # Новое поле
    client_email = models.EmailField(verbose_name="Почта клиента", blank=True, null=True)  # Новое поле
    client_comment = models.TextField(verbose_name="Комментарий клиента", blank=True)  # Новое поле

    class Meta:
        verbose_name = "Забронированное время"
        verbose_name_plural = "Забронированное время"
        ordering = ['date', 'time']
 
    def __str__(self): 
        return ''   

barbershop/templates/barbershop/barberbooking.html
{% extends 'barbershop/base.html' %}

{% load static %}

{% block main %}

<main class="main">   
    <section class="booking">
        <section class="booking_conteiner">
            <div class="wrapper">

                 <div class="block_title animation-bottom-to-up">
                    <img loading="lazy" src="{% static 'barbershop/img/services/icons_line1.png' %}" alt="inetiv.com">
                    <h2 class="block_title_main_text">БРОНИРУЙ СЕЙЧАС</h2>
                    <h4 class="block_title_second_text">Простой выбор мастера, услуги и времени</h4>
                    <img loading="lazy" src="{% static 'barbershop/img/services/icons_line2.png' %}" alt="inetiv.com_line2">
                    <a href="{% url 'verify' %}" class="checking_record_link"> ♦️ Нажмите, чтобы проверить свою запись</a>
                </div>

                <section class="booking_block">
                    {% for master in masters %}
                    <div class="booking_masters_block" id="Master_{{ master.id }}">

                        <section class="book_master_block">
                            <div class="book_master_img animation-bottom-to-up">
                                <img loading="lazy" class="animation-bottom-to-up" src="{{ master.avatar.url }}" alt="inetiv.com"> 
                            </div> 
                            
                            <div class="book_master_name">
                                <p data-master>{{ master.name }}</p> 
                            </div>
        
                            <p class="book_master_position">{{ master.specialty }}</p> 
        
                            <div class="book_master_social_network">
                                <a href="tel:{{ master.contact_set.first.phone }}"><img src="{% static 'barbershop/img/masters/icons-телефон.png' %}" alt="inetiv.com"></a>
                                <a href="{{ master.contact_set.first.telegram }}"><img src="{% static 'barbershop/img/masters/icons-телеграм.png' %}" alt="inetiv.com"></a>
                                <a href="{{ master.contact_set.first.instagram }}"><img src="{% static 'barbershop/img/masters/icons-instagram.png' %}" alt="inetiv.com"></a>
                                <a href="{{ master.contact_set.first.tiktok }}"><img src="{% static 'barbershop/img/masters/icons-тикток.png' %}" alt="inetiv.com"></a>
                            </div>
        
                            <button class="book_button" data-action="select-master">
                                <img loading="lazy" src="{% static 'barbershop/img/booking/arrow_black.png' %}" alt="inetiv.com_arrow">
                                <p >нажмите для выбора</p>
                            </button>
                        </section>
                
                        <section class="booking_services none">
                            <button class="book_button" data-action="back-to-masters">
                                <img loading="lazy" src="{% static 'barbershop/img/booking/arrow_left.png' %}" alt="inetiv.com_arrow">
                                <p >вернуться назад</p>
                            </button>
        
                            <div class="book_services_container">
                                {% for service in master.service_set.all %}
                                    <div class="book_service">
                                        <div class="book_service_info">
                                            <div class="book_service_text" data-selected="false">
                                                <div class="book_service_text_block">
                                                    <p class="book_service_name" data-service-name>{{ service.service_name }}</p> 
                                                    <p class="book_service_price">от <span data-price>{{ service.price }}</span> р, <span data-duration>{{ service.duration }}</span> минут</p> 
                                                </div>
                                                <div class="book_custom_checkbox"></div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
        
                            <button class="book_button" data-action="next-to-calendar">
                                <img loading="lazy" src="{% static 'barbershop/img/booking/finger_black.png' %}" alt="inetiv.com_arrow">
                                <p >далее ...</p>
                            </button>
                        </section>
                
                        <section class="booking_calendar none">
                            <button class="book_button" data-action="back-to-services">
                                <img loading="lazy" src="{% static 'barbershop/img/booking/arrow_left.png' %}" alt="inetiv.com_arrow">
                                <p >вернуться назад</p>
                            </button>
                
                            <div class="book_calendar_inner_block">
                                <div class="calendar" id="calendar_{{ master.id }}">
                                    <!-- -->
                                </div>

                                <div class="times"  id="times_{{ master.id }}">
                                    <p class="time_message">☝ Выберите дату</p>
                                    <!-- -->
                                </div>
                            </div>
                
                            <button class="book_button" data-action="next-to-form">
                                <img loading="lazy" src="{% static 'barbershop/img/booking/finger_black.png' %}" alt="inetiv.com_arrow">
                                <p>далее ...</p>
                            </button>
                        </section>
                    
                        <section class="booking_form_section none">
                            <button class="book_button" data-action="back-to-calendar">
                                <img loading="lazy" src="{% static 'barbershop/img/booking/arrow_left.png' %}" alt="inetiv.com_arrow">
                                <p>вернуться назад</p>
                            </button>
                
                            <div class="book_contact_form_block">
                                <div class="book_feedback_form_container">

                                    <div class="book_form_container">
                                        <img loading="lazy" class="feedback_form_icon" src="{% static 'barbershop/img/form-icon.png' %}" alt="">
                                        <form action="{% url 'send_booking_to_telegram' %}" class="book_form" method="post">
                                            {% csrf_token %}
                                            <div class="book_form_group">
                                                <input type="text" id="name" name="name" placeholder="Введите своё имя" maxlength="20" required>
                                            </div>
                                            
                                            <div class="book_form_group">
                                                <input type="tel" id="phone" name="phone" placeholder="Укажите телефон" maxlength="20" pattern="^\+?\d+$" title="Номер телефона может содержать только цифры и знак плюс" required>

                                            </div>
                                    
                                            <div class="book_form_group">
                                                <input type="email" id="email" name="email" placeholder="Введите email" maxlength="100" required>
                                            </div>
                                    
                                            <div class="book_form_group">
                                                <input type="text" id="comment" name="comment" placeholder="Добавьте комментарий" maxlength="200">
                                            </div>
                                    

                                            <div class="book_form_info_group">
                                                <div class="book_form_info">
                                                    <div class="book_form_input_container">Дата: <input type="text" id="date" name="date" value="" readonly></div>
                                                    <div class="book_form_input_container">Время: <input type="text" id="time" name="time" value="" readonly></div>
                                                </div>
                                            
                                                <div class="book_form_info">
                                                    <div class="book_form_input_container">Мастер: <input type="text" id="master" name="master" value="{{ master.name }}" readonly></div>
                                                </div>
                                            
                                                <div class="book_form_info">
                                                    <div class="book_form_input_container">Услуга: <input type="text" id="service" name="service" value="" readonly></div>
                                                </div>
                                            
                                                <div class="book_form_info">
                                                    <div class="book_form_input_container">~<input type="text" id="duration" name="duration" value="" readonly></div>
                                                    <div class="book_form_input_container">~ <input type="text" id="cost" name="cost" value="" readonly></div>
                                                </div>
                                            </div>

                                            <input type="hidden" id="master_id" name="master_id" value="{{ master.id }}" readonly>
                                            
                                            <button class="book_form_button" type="submit">ЗАКАЗАТЬ</button>
                                        </form>
                                    </div>
                                    

                                    <img loading="lazy" class="feedback_form_icon" src="{% static 'barbershop/img/form-icon.png' %}" alt="inetiv.com_line2">
                
                                </div>
                            </div>
                        </section>
                    </div>
                    {% endfor %}

                </section>
                
            </div>
        </section>
    </section>

    <script src="{% static 'barbershop/js/main.js' %}"></script>    
    <script src="{% static 'barbershop/js/booking.js' %}"></script>      
    
    <script src="{% static 'barbershop/js/textwritter.js' %}"></script>  
    <script src="{% static 'barbershop/js/delayedLoading.js' %}"></script>  
    

</main>

{% endblock main %}

barbershop/templates/barbershop/base.html
{% load static %}  

<!DOCTYPE html>
<html>
	<head>
		<title>iNetiv.com - barbershop</title>
        <link rel="icon" type="image/png" href="{% static 'barbershop/img/icon_marks.png' %}">

        <link type="text/css" href="{% static 'barbershop/css/null.css' %}" rel="stylesheet" />
        <link type="text/css" href="{% static 'barbershop/css/font.css' %}" rel="stylesheet" />
        <link type="text/css" href="{% static 'barbershop/css/header.css' %}" rel="stylesheet" />
        <link type="text/css" href="{% static 'barbershop/css/main.css' %}" rel="stylesheet" />
        <link type="text/css" href="{% static 'barbershop/css/other_blocks.css' %}" rel="stylesheet" />
        <link type="text/css" href="{% static 'barbershop/css/footer.css' %}" rel="stylesheet" />
        <link type="text/css" href="{% static 'barbershop/css/mobile_style.css' %}" rel="stylesheet" />
        <link type="text/css" href="{% static 'barbershop/css/slider_main.css' %}" rel="stylesheet" />
        <link type="text/css" href="{% static 'barbershop/css/dropdownmenu.css' %}" rel="stylesheet" />
        <link type="text/css" href="{% static 'barbershop/css/form.css' %}" rel="stylesheet" />
        <link type="text/css" href="{% static 'barbershop/css/photo_slider.css' %}" rel="stylesheet" />
        <link type="text/css" href="{% static 'barbershop/css/marketing.css' %}" rel="stylesheet" />
        <link type="text/css" href="{% static 'barbershop/css/header.css' %}" rel="stylesheet" />
        <link type="text/css" href="{% static 'barbershop/css/main.css' %}" rel="stylesheet" />
        <link type="text/css" href="{% static 'barbershop/css/other_blocks.css' %}" rel="stylesheet" />
        <link type="text/css" href="{% static 'barbershop/css/footer.css' %}" rel="stylesheet" />
        <link type="text/css" href="{% static 'barbershop/css/mobile_style.css' %}" rel="stylesheet" />
        <link type="text/css" href="{% static 'barbershop/css/slider_main.css' %}" rel="stylesheet" />
        <link type="text/css" href="{% static 'barbershop/css/dropdownmenu.css' %}" rel="stylesheet" />
        <link type="text/css" href="{% static 'barbershop/css/form.css' %}" rel="stylesheet" />
        <link type="text/css" href="{% static 'barbershop/css/photo_slider.css' %}" rel="stylesheet" />
        <link type="text/css" href="{% static 'barbershop/css/marketing.css' %}" rel="stylesheet" />
        <link type="text/css" href="{% static 'barbershop/css/booking.css' %}" rel="stylesheet" />
        <link type="text/css" href="{% static 'barbershop/css/verify.css' %}" rel="stylesheet" />
        <link type="text/css" href="{% static 'barbershop/css/delayedLoading.css' %}" rel="stylesheet" />
        
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"> 
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>
	<body>

		{% block header %}
        <header class="header">
            <section class="header_info_block">
                {% if data %}
                <div class="header_preview">
        
                    <a href="{{ location }}" class="header_preview_block">
                        <img src="{% static 'barbershop/img/header_img/geolocation.png' %}" alt="geolocation">
                        
                        <div class="header_preview_mini_block">
                            <p>Адрес</p>
                            <p>{{ data.address |safe }}</p>
                        </div>  
                    </a>
        
                    <a href="tel:+74951234567" class="header_preview_block">
                        <img src="{% static 'barbershop/img/header_img/phone.png' %}" alt="phone">
                        
                        <div class="header_preview_mini_block">
                            <p>Телефон</p>
                            <p href="tel:{{ data.phone }}">{{ data.phone |safe }}</p>
                        </div>  
                    </a>
        
                    <a href="{{ work_time }}" class="header_preview_block">
                        <img src="{% static 'barbershop/img/header_img/time.png' %}" alt="time_work">
                        
                        <div class="header_preview_mini_block">
                            <p>Режим работы</p>
                            <p>{{ data.working_hours |safe }}</p>
                        </div>  
                    </a>
        
                </div>
                {% else %}
                    <p>Данные отсутствуют.</p>
                {% endif %}
    
            </section>
    
            <section class="header_menu_block">
                <div class="header_menu_wrapper">
                    <a href="{% url 'barbershop' %}" class="header_logo_block">
                        <img src="{% static 'barbershop/img/header_img/logo1.png' %}" alt="inetiv_barber_logo">
                        <p class="header_logo_text">"Интроверт"</p>
                    </a>

                    <nav class="header__menu"> 
                        <ul class="header__list">
                            <li><a href="{% url 'barbershop' %}">ГЛАВНАЯ</a></li>
                            <li><a href="{{ main_services }}">УСЛУГИ</a></li>
                            <li><a href="{{ main_masters }}">МАСТЕРА</a></li>
                            <li><a href="{% url 'barberbooking' %}">ЗАПИСЬ</a></li>
                            <li><a href="{{ main_contact }}">КОНТАКТЫ</a></li>
                            <li><a href="{{ main_foto }}">ФОТО</a></li>
                            <li><a href="{{ main_feedback }}">ОТЗЫВЫ</a></li>
                        </ul>
                    </nav> 

                    <div class="header__burger"> 
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
            </section>

        </header>
		{% endblock header %}


		{% block main %}
	
		{% endblock main %}


        {% block footer %}
        <footer class="footer">
            <div class="wrapper">
                <div class="main_footer">
                    <a class="footer_title" href="{% url 'barbershop' %}">
                        <img loading="lazy" src="{% static 'barbershop/img/logo2.png' %}" alt="inetiv.com_title_barbershop">
                        <p>БАРБЕРШОП "ИНТРОВЕРТ</p>
                    </a>

                    <a class="privacy_policy_link" href="{% url 'privacy_policy' %}">
                        Политика конфиденциальности
                    </a>
        
                    <div class="footer_links">
                        <a href="{% url 'barbershop' %}" class="footer_link">ГЛАВНАЯ</a>
                        <a href="{{booking}}" class="footer_link">ЗАПИСЬ</a>
                        <a href="{{ main_contact }}" class="footer_link">КОНТАКТЫ</a>
                    </div>
                </div>
            </div>

            <div class="inetiv_com_link">
                <p class="footer_copyright">Ⓒ Все права защищены</p>
                <div class="footer_authors_link">
                    <a href="https://inetiv.com/" class="website_developer">iNetiV.com </a>
                    <a href="https://inetiv.com/" id="textwritter"></a>
                </div>
            </div>
        </footer>
        {% endblock footer %}
	</body>
</html>

barbershop/templates/barbershop/confirmation.html
{% extends 'barbershop/base.html' %}

{% load static %}

{% block main %}

<main class="main">   
    <section class="booking">
        <section class="booking_conteiner">
            <div class="wrapper">

                 <div class="block_title">
                    <img src="{% static 'barbershop/img/services/icons_line1.png' %}" alt="inetiv.com">
                    <h2 class="block_title_main_text">СТАТУС ЗАПИСИ</h2>
                    <h4 class="block_title_second_text">Давайте убедимся, что все готово для вашего визита!</h4>
                    <img src="{% static 'barbershop/img/services/icons_line2.png' %}" alt="inetiv.com_line2">
                </div>

                <section class="confirmation_block">
                    <h2 class="confirmation_title">Ваша заявка успешно отправлена!</h2>
                
                    <div class="confirmation_client">
                        <p>Спасибо, <span>{{ name }}</span>, что выбрали нас! </p>
                    </div>
                
                    <div class="confirmation_message">
                        <p>Наш мастер подтвердит вашу заявку в течение <span>двух часов.</span></p>
                        <p>Мы приложим все усилия, чтобы сделать ваш визит приятным и комфортным.</p>
                        <p>В случае возникновения вопросов, мы свяжемся с вами по указанному номеру телефона <span> +{{phone}}</span>.</p>
                        <p>Проверить статус записи можно самостоятельно по 
                            <a href="{% url 'verify' %}" class="confirmation_record_link">ссылке</a>.
                        </p>
                    </div>
                </section>
            </div>
        </section>

    </section>

    <script src="{% static 'barbershop/js/main.js' %}"></script>      
    <script src="{% static 'barbershop/js/textwritter.js' %}"></script>  

    

</main>

{% endblock main %}

barbershop/templates/barbershop/verify.html
{% extends 'barbershop/base.html' %}

{% load static %}

{% block main %}

<main class="main">   
    <section class="booking">
        <section class="booking_conteiner">
            <div class="wrapper">

                 <div class="block_title">
                    <img src="{% static 'barbershop/img/services/icons_line1.png' %}" alt="inetiv.com">
                    <h2 class="block_title_main_text">СТАТУС ЗАПИСИ</h2>
                    <h4 class="block_title_second_text">Давайте убедимся, что все готово для вашего визита!</h4>
                    <img src="{% static 'barbershop/img/services/icons_line2.png' %}" alt="inetiv.com_line2">
                </div>

                <section class="booking_block">

                    <div class="check-record-container">
                        <p class="check-record-description">Введите последние 6 цифр вашего номера телефона, чтобы узнать о вашей записи:</p>

                        <div class="check-record-input">
                            <input type="text" id="phone-input" maxlength="6" placeholder="Введите последние 6 цифр" />
                            <button id="check-button">Проверить</button>
                        </div>
                        
                        <div id="result-message" class="result-message hidden">
                            <!-- -->
                        </div>

                        <p class="check-record-description">* Запись подтверждается мастером в течение двух часов с момента её подачи.</p>
                    </div>


                    
                </section>
                

            </div>
        </section>

    </section>

    <script src="{% static 'barbershop/js/main.js' %}"></script>      
    <script src="{% static 'barbershop/js/verify.js' %}"></script>    
    <script src="{% static 'barbershop/js/textwritter.js' %}"></script>  

    

</main>

{% endblock main %}